defaults: [ default ]

model_class: src.models.mgfn.modeling_mgfn.MGFNForVideoAnomalyDetection

model_config:
  _target_: src.models.mgfn.configuration_mgfn.MGFNConfig
  dims: [64, 128, 1024]
  depths: [3, 3, 2]
  mgfn_types: [gb, fb, fb]
  lokernel: 5
  channels: 2048
  ff_repe: 4
  dim_head: 64
  local_aggr_kernel: 5
  dropout: 0.0
  attention_dropout: 0.0
  dropout_rate: 0.7
  mag_ratio: 0.1
  k: 3